name: CI
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install linters
        run: |
          python -m pip install -U pip
          pip install ruff mypy coverage
          sudo npm -g i markdownlint-cli || true
          sudo apt-get update
          sudo apt-get install -y yamllint || true
          curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download/actionlint.bash | bash -s -- -b "$PWD/bin"
          echo "$PWD/bin" >> $GITHUB_PATH
      - name: Run linters
        run: |
          ruff check .
          ./bin/actionlint || true
          markdownlint "**/*.md" || true
          yamllint . || true

  test-python:
    if: ${{ hashFiles('**/*.py') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest coverage mypy ruff
      - name: Pytest
        run: pytest -q

  test-shell:
    runs-on: ubuntu-latest
    container: bats/bats:1.11.0
    steps:
      - uses: actions/checkout@v4
      - name: Ensure smoke test
        run: |
          mkdir -p tests/shell
          if ! ls tests/shell/*.bats >/dev/null 2>&1; then
            cat > tests/shell/00_smoke.bats <<'EOF'
#!/usr/bin/env bats
@test "shell test harness is alive" {
  run bash -lc 'echo ok'
  [ "$status" -eq 0 ]
  [ "$output" = "ok" ]
}
EOF
            chmod +x tests/shell/00_smoke.bats
          fi
      - name: ShellCheck (warnings only fail if configured)
        run: |
          shopt -s globstar nullglob
          files=( **/*.sh )
          if [ ${#files[@]} -gt 0 ]; then
            shellcheck -S warning "${files[@]}"
          else
            echo "No shell files found."
          fi
      - name: Run Bats
        run: bats tests/shell
