name: CI

on:
  push:
    paths:
      - 'scripts/cp_layouts.py'
      - 'cyberplasma/scripts/*.sh'
      - 'tests/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'scripts/cp_layouts.py'
      - 'cyberplasma/scripts/*.sh'
      - 'tests/**'
      - '.github/workflows/ci.yml'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Run ShellCheck
        run: shellcheck cyberplasma/scripts/*.sh

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run pytest
        run: python -m pytest

  shell-tests:
    runs-on: ubuntu-latest
    container: bats/bats:1.11.0
    steps:
      - uses: actions/checkout@v4
      - name: Ensure shell tests
        run: |
          mkdir -p tests/shell
          if [ -z "$(find tests/shell -name '*.bats' -print -quit)" ]; then
            cat <<'TEST' > tests/shell/00_smoke.bats
#!/usr/bin/env bats
@test "smoke test" {
  true
}
TEST
          fi
      - name: Run Bats tests
        run: bats tests/shell
