name: Shellcheck

on:
  push:
    paths:
      - 'cyberplasma/scripts/*.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    paths:
      - 'cyberplasma/scripts/*.sh'
      - '.github/workflows/shellcheck.yml'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run shellcheck
        run: shellcheck cyberplasma/scripts/*.sh
