name: CI

on:
  push:
    paths:
      - 'scripts/cp_layouts.py'
      - 'cyberplasma/scripts/*.sh'
      - 'tests/**'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    paths:
      - 'scripts/cp_layouts.py'
      - 'cyberplasma/scripts/*.sh'
      - 'tests/**'
      - '.github/workflows/shellcheck.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck bats python3-pip
          python3 -m pip install pytest
      - name: Run ShellCheck
        run: shellcheck cyberplasma/scripts/*.sh
      - name: Run pytest
        run: python3 -m pytest
      - name: Run Bats tests
        run: bats tests/shell
